### PR TITLE
flake improvements

### PR DESCRIPTION
**Pull request by disassembler**
* exposes project from haskell.nix at top level
* adds work-around so `--update-input` with CHaP works as expected

# Changelog

```yaml
- description: |
    Flake improvements:
    - exposes project from haskell.nix at top level
    - adds work-around so --update-input with CHaP works as expected
  compatibility: no-api-changes
  type: maintenance
```

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
- [ ] Any changes are noted in the `CHANGELOG.md` for affected package
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG node developers to do this
for you.

### CODE REVIEW

**Review by angerman — APPROVED** [review]
LGTM

Although the CHaP workaround could be better in explaining _why_ this is necessary right now.

**Review by newhoggy — APPROVED** [review]

**Comment by newhoggy** [comment]
Merging, but @disassembler can you please add an explanation as suggested by @angerman to the PR?

**Comment by hamishmack** [comment]
From #69:

This helps haskell.nix find the package source correctly.  In particular new packages that are not in the main CHaP branch yet will be loaded correctly.

To try it out you will need a local CHaP, this can be build with:

```
git clone git@github.com:input-output-hk/cardano-haskell-packages.git
cd cardano-haskell-packages
nix develop -c foliage build -j 0 --write-metadata
```

That will make a `cardano-haskell-packages/_repo` dir with the CHaP repository including any new packages.  To use from a directory containing this `cardano-api` branch run:

```
nix build --override-input CHaP path:/home/hamish/iohk/cardano-haskell-packages/_repo .\#hydraJobs.required
```

Make sure to use `path:` and the full path to the `_repo` directory.

**Comment by hamishmack** [comment]
Also we can update this once https://github.com/input-output-hk/haskell.nix/pull/1984 is merged.

**Pull request merged**
